export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_PENDING = ' GET_COMMENTS_PENDING';
export const GET_COMMENTS_FULFILLED = 'GET_COMMENTS_FULFILLED';

export const GET_COMMENTS_FOR_POST = 'GET_COMMENTS_FOR_POST';
export const GET_COMMENTS_FOR_POST_PENDING = ' GET_COMMENTS_FOR_POST_PENDING';
export const GET_COMMENTS_FOR_POST_FULFILLED = 'GET_COMMENTS_FOR_POST_FULFILLED';
